version: '3'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: 'yourStrong(!)Password'
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
    restart: always
