version: '3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.1.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:5.1.0'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
  schema-registry:
    image: 'confluentinc/cp-schema-registry:5.3.0'
    hostname: schema-registry
    ports:
      - "8083:8083"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:19092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8083
    depends_on:
      - zookeeper
      - kafka
  api:
    image: 'confluentinc/cp-kafka-rest'
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8083/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:19092
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
  topics-ui:
    image: 'landoop/kafka-topics-ui'
    environment:
      KAFKA_REST_PROXY_URL: 'http://localhost:8082'
      PROXY: 'false'
    ports:
      - "8000:8000"
